server:
  port: 8000

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8100/eureka/

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/liazhan/shop-project-config # 配置git仓库的地址
          search-paths: common,eureka,gateway,member,weixin # git仓库地址下的相对地址，可以配置多个，用,分割。
    bus:
      enabled: true
      trace:
        enabled: true
  rabbitmq:
    host: 47.98.183.103
    port: 5672
    username: user
    password: password
management:
  endpoints:
    web:
      exposure:
        include: "*"



