#服务端口号
server:
  port: 8200
#eureka信息配置
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8100/eureka
spring:
  application:
    name: liazhan-weixin

####swagger相关配置
swagger:
  base-package: com.liazhan.weixin.service
  title: 微服务电商项目-微信服务接口
  description: 微信服务
  version: 1.1
  terms-of-service-url: www.baidu.com
  contact:
    name: liazhan
    email: 33421352+liazhan@users.noreply.github.com